<Project>
	<PropertyGroup>
		<RepoRootPath>$(MSBuildThisFileDirectory)</RepoRootPath>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<EnableDynamicPlatformResolution>true</EnableDynamicPlatformResolution>
		<GitVersionBaseDirectory>$(MSBuildThisFileDirectory)</GitVersionBaseDirectory>
		<PackageOutputPath>$(RepoRootPath)bin\Packages\$(Configuration)\</PackageOutputPath>
	</PropertyGroup>
	<PropertyGroup>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
	</PropertyGroup>
	<PropertyGroup>
		<Product>AnakinRaW Common Utilities</Product>
		<Copyright>Copyright © AnakinRaW 2026</Copyright>
		<Authors>AnakinRaW</Authors>
		<Owners>AnakinRaW</Owners>
		<PackageProjectUrl>https://github.com/AnakinRaW/CommonUtilities</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="SauceControl.InheritDoc" Version="2.0.2" PrivateAssets="all" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Nerdbank.GitVersioning" Condition="!Exists('packages.config')">
			<PrivateAssets>all</PrivateAssets>
			<Version>3.10.91</Version>
		</PackageReference>
		<None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>