<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Title>CommonUtilities.Registry</Title>
		<PackageId>AnakinRaW.CommonUtilities.Registry</PackageId>
		<Description>Platform independent abstraction layer for the Windows Registry.</Description>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
		<RootNamespace>AnakinRaW.CommonUtilities.Registry</RootNamespace>
		<AssemblyName>AnakinRaW.CommonUtilities.Registry</AssemblyName>
		<NeutralLanguage>en</NeutralLanguage>
	</PropertyGroup>

	<PropertyGroup>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<InheritDocEnabled>true</InheritDocEnabled>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" Condition="$(TargetFramework) == 'netstandard2.0'" />
		<PackageReference Include="System.Memory" Version="4.6.3" Condition="$(TargetFramework) == 'netstandard2.0'" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Nullable" Version="1.3.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.102" />
	</ItemGroup>

</Project>
