name: Deploy

on:
  workflow_call:

env:
  solution: "CommonUtilities.sln"
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  PACKAGE_OUTPUT_DIR: ${{ github.workspace}}/nupkgs

jobs:
  deploy:
    name: Pack & Deploy Release
    runs-on: ubuntu-latest
            
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build & Test
        run: dotnet pack ${{ env.solution }} --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output ${{ env.PACKAGE_OUTPUT_DIR }}

      - name: Publish to Nuget
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}/**/*.nupkg  --source ${{ env.NUGET_SOURCE_URL }} --api-key ${{ secrets.NUGETAUTHKEY }} --skip-duplicate
