name: Tag

on:
  workflow_call:

jobs:
  tag:
    name: Tag Repository
    runs-on: ubuntu-latest        
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - id: create-tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main