name: Build-Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-test:
    name: Build & Test CommonUtilities
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-framework: [net6.0, net48]
        exclude:
          - os: ubuntu-latest
            dotnet-framework: net48
      fail-fast: false
    runs-on: ${{ matrix.os }}

    env:
      solution: "CommonUtilities.sln"
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        
      - name: Build & Test
        run: dotnet test ${{ env.solution }} -c Release -f ${{ matrix.dotnet-framework }}